name: Java CI - Test

on: 
  pull_request:
  schedule:
    - cron: "0 2 * * 1-5"

jobs:
  test:

    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 2
      matrix:
        java: [1.8, 1.11]
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use ${{ matrix.os }} for JAVA 1.8
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: tests RUN
      run: mvn clean compile test site --file pom.xml
    - uses: actions/upload-artifact@v1
      with:
        name: artifacts
        path: target
    - uses: actions/download-artifact@master
      with:
        name: artifacts
        path: artifacts
    
    - name: Show folder files
      run: ls
